# More info: https://www.serverless.com/framework/docs/

# Example

# service: app
# provider:
#   name: aws
#   runtime: nodejs12.x
#   region: eu-west-2
#   stage: ${opt:stage, self:custom.defaultStage}
#   memorySize: 128

# custom:
#   defaultStage: staging

# functions:
#   app:
#     handler: app/app.handler
#     events:
#       - http:
#           path: /
#           method: ANY
#           cors: true
#       - http:
#           path: /{proxy+}
#           method: ANY
#           cors: true